module.exports = Object.freeze({
  asthmaDiagnosis: {
    1: 'Asthma as main diagnosis',
    2: 'Asthma as secondary diagnosis',
  },
  ageClass: {
    2: '18-49',
    3: '50-64',
    4: '65-79',
    5: 'More than 80',
  },
  outcome: {
    1: 'Cost',
    2: 'Length of stay',
    3: 'In-hospital mortality',
  },
  asthmaSecondDiagnosis: {
    1: 'Yes',
    2: 'Other',
  },
  comorbidities: {
    0: 'None',
    1: 'Myocardial infarction',
    2: 'Congestive heart failure',
    3: 'Peripheral vascular disease',
    4: 'Cerebrovascular disease',
    5: 'Dementia',
    6: 'Chronic pulmonary disease',
    7: 'Rheumatic disease',
    8: 'Peptic ulcer disease',
    9: 'Mild liver disease',
    10: 'Diabetes without chronic complication',
    11: 'Diabetes with chronic complication',
    12: 'Hemiplegia or paraplegia',
    13: 'Renal disease',
    14: 'Cancer',
    15: 'Moderate or severe liver disease',
    16: 'Metastatic solid tumor',
    17: 'HIV',
    18: 'Asthma',
  },
});
