name: main
on:
  push:
    branches:
      - main

jobs:
  npm-build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: NPM Install
        run: npm ci

      - name: NPM Build
        run: npm run build
      
      - name: Git Commit
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
          with:
            commit_message: Automated build
